version: '3.4'
services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - dbdata:/var/lib/postresql/data
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db

volumes:
  dbdata:
    name: cms-dal-db
